### PR TITLE
Fixing type issues in van_jsx

### LINKED ISSUE #138: TypeScript error when using State inside JSX element
When using van_jsx, I noticed that using a state as an element child will cause a TypeScript error:
**Type 'State<number>' is not assignable to type 'ComponentChild'.**

The issue was solved very simply by adding the Sate type imported from `vanjs-core` to the ComponentChild type in `type.d.ts`: 
Before: 
export type ComponentChild =
  | FunctionChild<any>
  | Element
  | string
  | number
  | bigint
  | boolean
  | null
  | undefined;

After - this solves the problem:
export type ComponentChild =
  | FunctionChild<any>
  | Element
  | string
  | number
  | bigint
  | boolean
  | null
  | undefined 
  | State

### PR DESCRIPTION
**Pull request by yahia-berashish**
fixes #138

### CODE REVIEW

**Comment by cqh963852** [comment]
LGTM @Tao-VanJS PTAL

File: addons/van_jsx/src/type.d.ts [hunk 1]
```diff
@@ -1,16 +1,23 @@
+import { State, ChildDom } from "vanjs-core";
+
+type VanElement = Element | ChildDom;
```
Comment (Tao-VanJS) [inline addons/van_jsx/src/type.d.ts:3]: Do you need VanElement? I think ChildDom is a super type of Element (ChildDom > Node > Element).

Comment (yahia-berashish) [reply addons/van_jsx/src/type.d.ts:3]: Right, I was in a hurry and didn't consider that, will resolve, just not right now.

Comment (yahia-berashish) [reply addons/van_jsx/src/type.d.ts:3]: > Do you need VanElement? I think ChildDom is a super type of Element (ChildDom > Node > Element).

In that case, should the whole ComponentChildren type be just replaced with ChildDom @cqh963852 @Tao-VanJS ?

Comment (Tao-VanJS) [reply addons/van_jsx/src/type.d.ts:3]: I think `ComponentChildren` should be replaced with `ChildDom`. Technically is `ComponentChildren` a super type of `ChildDom` because the return type of `FunctionChild<P>` is broader than `BindingFunc` defined in VanJS. But this is probably not what we want. A function that returns another function is not a valid binding function in VanJS anyway.

File: addons/van_jsx/src/jsx-internal.d.ts [hunk 2]
```diff
@@ -1,19 +1,19 @@
 import * as CSS from "csstype";
-import { State } from "vanjs-core";
-import { ComponentChildren, FunctionChild } from "./type";
+import { State, ChildDom } from "vanjs-core";
+import { FunctionChild } from "./type";
 
 type OriginalElement = HTMLElement;
```
Comment (Tao-VanJS) [inline addons/van_jsx/src/jsx-internal.d.ts:5]: Is this line really needed. Can we simply use `HTMLElement` whenever `OriginalElement` is referred?

**Review by Tao-VanJS — APPROVED** [review]
@yahia-berashish

I will merge this PR.

But I left a comment. Will appreciate if you can take a look when you have a chance.

**Comment by Tao-VanJS** [comment]
@allcontributors please add @yahia-berashish for bug, code, plugin

File: addons/van_jsx/src/jsx-internal.d.ts (hunk 2 above)
Comment (Tao-VanJS) [reply addons/van_jsx/src/jsx-internal.d.ts:5]: @cqh963852, what's your opinion? Can we get the line removed?

Comment (cqh963852) [reply addons/van_jsx/src/jsx-internal.d.ts:5]: It can be removed
